Analysing all simple paths in the structural network to the functional user movement data
alphagov/single-data-environment-user-journeys pull request #3
Opened 2022-07-08 12:14 UTC by st-alice

# Summary
This PR relates to creating the 'intended user journeys' in the structural network, and comparing this to the data in the functional network. For this, I have created a notebook where you can call and run the appropriate functions from. 

There are X number of scripts to check: 
- `src/make_data/create_intended_journeys.py`: this includes two functions which finds all simple paths and ranks all simple paths. `find_simple_paths` provides us with the intended journeys. As this can be many journeys, `rank_simple_paths` enables you to rank the intended journey. You can try different methods to do this. 

- `notebooks/run_intended_journeys.ipynb`: a notebook to run the functions from.

- `src/make_utils/analyse_intended_journeys.py`: 

# Checklists

This pull/merge request meets the following requirements:

- [X] code runs
- [X] developments are ethical][data-ethics-framework] and secure
- [X] you have made proportionate checks that the code works correctly
- [ ]~~ test suite passes ~~ No tests
- [X] developments adhere to AQA plan (see `docs/aqa/aqa_plan.md`)
- [ ]~~ data log updated (see `docs/aqa/data_log.md`), if necessary ~~ not neccessary
- [ ] ~~assumptions, and caveats log updated (see `docs/aqa/assumptions_caveats.md`), if
  necessary ~~ assumptions on the scripts. 
- [ ] ~~ [minimum usable documentation][agilemodeling] written in the `docs` folder ~~ to be updated as the last step

Comments have been added below around the incomplete checks.

[agilemodeling]: http://agilemodeling.com/essays/documentLate.htm
[data-ethics-framework]: https://www.gov.uk/government/publications/data-ethics-framework

2022-08-10 15:31 UTC, nacnudus reviewed
This is only a partial review, which I'll return to on Monday.  The extensive docstrings are very helpful, and the examples made it much easier to review the code.

2022-08-10 15:31 UTC, nacnudus commented on src/make_data/create_intended_journeys.py
> +            journeys_ranked_dict[key.replace(" ", ", ")] = value
I think this could be simplified  The function `nx.pagerank` could be passed by the user, e.g. `rank_simple_paths(nx.pagerank, G, all_simple_paths, verbose=0)`.  That would avoid the need for the `if ... elif` statement.

```py
    # Or, rank all page paths by a given method
    if method == "pageRank":
        ranking_method = nx.pagerank(G)
    elif method == "betweenness":
        ranking_method = nx.betweenness_centrality(G)
    elif method == "closeness":
        ranking_method = nx.closeness_centrality(G)
    elif method == "eigenvector":
        ranking_method = nx.eigenvector_centrality(G)
```

So that block, above, could be simply `scores = method(G)`.

The remainder can also be simpler, I think.

```py
        scores = method(G)

        mean_scores = [
            sum([scores[url] for url in urls]) / len(urls)
            for urls in all_simple_paths
        ]

        sorted_paths = [all_simple_paths[i] for i in np.argsort(mean_scores)]

        mean_scores.sort()

        journeys_ranked_dict = {
            ','.join(urls): score
            for urls, score in zip(sorted_paths, mean_scores)
        }
```

Or even `return sorted_paths` if the dictionary isn't required.

2022-08-15 09:12 UTC, nacnudus reviewed
A bit more of a review, still incomplete.  Mainly suggestions to use existing python features to save work.

2022-08-15 09:12 UTC, nacnudus commented on src/make_data/create_intended_journeys.py
> +    for ind, path in enumerate(all_simple_paths):
[`islice()`](https://docs.python.org/3/library/itertools.html#itertools.islice) and [`pairwise()`](https://docs.python.org/3/library/itertools.html#itertools.pairwise) could be useful here.

2022-08-15 09:12 UTC, nacnudus commented on src/utils/analyse_intended_journeys.py
> +def show_graph(G, labels=False):
I'm not completely sure of the syntax, but I think `**kwargs` would allow `show_graph()` to support all the keyword arguments of `nx.draw()`, not just `labels`.

```
def show_graph(G, **kwargs):
    return nx.info(G), nx.draw(G, **kwargs)
```

2022-08-15 10:15 UTC, nacnudus commented on src/make_data/create_intended_journeys.py
> +    Rank the order of all simple paths by a given method.
It might also be quicker, because it uses a different algorithm.

2022-08-15 12:42 UTC, nacnudus requested changes
Third tranche of this ongoing review.  Only the notebook is yet to be checked.

2022-08-15 12:42 UTC, nacnudus commented on src/utils/analyse_intended_journeys.py
> +            result = string1 in string2
Unfortunately, `"https://www.gov.uk, https://www.gov.uk/a"` is in `"https://www.gov.uk, https://www.gov.uk/a/b"`.

The journeys must be compared while they are still arrays of individual URLs, before they are concatenated into comma-separated strings.  This might help https://stackoverflow.com/a/3314913.  Or do the check in the graph, rather than in the data frame. https://stackoverflow.com/a/51638680.

2022-08-15 12:42 UTC, nacnudus commented on src/make_visualisations/create_network_plot.py
> +    node_highlight_colour = "white"
Strongly approve :+1:

2022-08-15 12:42 UTC, nacnudus commented on src/make_visualisations/create_network_plot.py
> +
Could this be in the notebook instead?

2022-08-15 13:12 UTC, nacnudus requested changes
Final tranche of this review.  The introduction to the notebook is very clear, and explains the design and assumptions to an appropriate level of detail.

I've asked some questions about how node centrality works in special cases, but the only thing in this part of the review that needs addressing before merging is the `git clone` command.

2022-08-15 13:12 UTC, nacnudus commented on notebooks/create_and_analyse_intended_journeys.ipynb
> +    "]\n",
If performance is a concern, then this could be done in other ways.

- Instead of `include_pages`, construct separate sets of simple paths to and from each page in `include_pages`, then combine them.
- Instead of `exclude_pages`, omit those pages from the graph before searching for simple paths.

2022-08-15 13:12 UTC, nacnudus commented on notebooks/create_and_analyse_intended_journeys.ipynb
> +    "# 4.1.1: Create Bokeh plot visualising the structural and functional networks\n",
Would Markdown's subheadings be appropriate here, e.g.

# title

## 1. section

### 1.2 subsection

#### 1.2.3 subsubsection

2022-08-15 13:13 UTC, nacnudus commented
@st-alice I really enjoyed reviewing this PR, and your presentations on the same topic.  I didn't know about simple paths before -- they're a clever way to infer intended user journeys.  Your comprehensive docstrings put me to shame.

2022-08-16 16:23 UTC, st-alice reviewed
Many thanks @nacnudus for your thorough and insightful review. I have only responded to half of the comments and will finish the response tomorrow.

2022-08-16 16:23 UTC, st-alice commented on src/make_data/create_intended_journeys.py
> +    Rank the order of all simple paths by a given method.
Many thanks for making me aware of this function. 

`nx.shortest_simple_paths()` takes an edge weight, and as this is a directed graph, this is a directed graph problem, where the weights of all edges coming into a node are equal to that node's weight.

Replacing all of this function with this simple code (for page rank only): 

```
# add node weight as page rank 
ranking = nx.pagerank(G)

# for each edge, take the page rank of the incoming node, 
# and add as edge weight

for edge in G.edges(data=True):
    G[edge[0]][edge[1]]['weight'] = ranking[edge[0]]

# find shortest simple paths with weight 
list(nx.shortest_simple_paths(G, source, target, weight='weight'))
```

... provides a better output for the accounts domain data. For example, where:

```
source = "https://www.gov.uk/email/subscriptions/single-page/new"
target = "https://www.gov.uk/email/subscriptions/account/confirm"
```

the top 2 journeys are in the original code are: 

```
[https://www.gov.uk/email/subscriptions/single-page/new', 'https://www.gov.uk/sign-in', 
'https://www.gov.uk/email/manage', 'https://www.gov.uk/account/home', 'https://account.gov.uk/manage-your-account', 'https://signin.account.gov.uk/signed-out', 'https://signin.account.gov.uk/sign-in-or-create', 'https://signin.account.gov.uk/enter-email', 'https://signin.account.gov.uk/enter-password', 'https://www.gov.uk/email/subscriptions/account/confirm']

['https://www.gov.uk/email/subscriptions/single-page/new', 'https://www.gov.uk/sign-in, https://www.gov.uk/email/manage', 'https://account.gov.uk/manage-your-account', 'https://www.gov.uk/account/home', 'https://signin.account.gov.uk/signed-out', 'https://signin.account.gov.uk/sign-in-or-create', 'https://signin.account.gov.uk/enter-email', 'https://signin.account.gov.uk/enter-password', 'https://www.gov.uk/email/subscriptions/account/confirm']
```

whereas with the new code, the top 2 journeys are: 

```
[https://www.gov.uk/email/subscriptions/single-page/new',
  'https://signin.account.gov.uk/sign-in-or-create',
  'https://signin.account.gov.uk/enter-email',
  'https://signin.account.gov.uk/enter-password',
  'https://www.gov.uk/email/subscriptions/account/confirm']
 
[https://www.gov.uk/email/subscriptions/single-page/new',
  'https://signin.account.gov.uk/sign-in-or-create',
  'https://signin.account.gov.uk/enter-email-create',
  'https://signin.account.gov.uk/check-your-email',
  'https://signin.account.gov.uk/create-password',
  'https://signin.account.gov.uk/enter-phone-number',
  'https://signin.account.gov.uk/check-your-phone',
  'https://signin.account.gov.uk/account-created',
  'https://www.gov.uk/email/subscriptions/account/confirm]
```

... these two journeys are the two journeys we would expect.

I am keen to change this whole function to the above new code (even due to the simplicity of it). I won't respond to the other comments unless you object to me using the `nx.shortest_simple_paths()` function rather than the original code. 

Thanks!

2022-08-16 16:23 UTC, st-alice commented on src/make_data/create_intended_journeys.py
> +            if index <= len(path) - 1:
Agreed - I think this was left over when I was testing the code. Removed redundant if statement in commit ed50a42d229bf8b7d431379e33d6ed6c525dbe2a

2022-08-16 16:23 UTC, st-alice commented on src/make_data/create_intended_journeys.py
> +    for ind, path in enumerate(all_simple_paths):
Many thanks for telling me about these functions - I did not know they existed. I think the code is quite simple and readable so I will leave as it is, but good to know for future about using `islice` to iterate over particular elements (i.e when index != 0). Thank you!

2022-08-16 16:24 UTC, st-alice commented on src/make_data/create_intended_journeys.py
> +    target. There may be large number of simple paths in a graph.
It sure does! Updated in commit [cd498d6](https://github.com/alphagov/single-data-environment-user-journeys/pull/3/commits/cd498d6d2faa29f1fe2ddb1637bdc65bbbea66d0)

2022-08-17 14:11 UTC, st-alice commented on src/utils/analyse_intended_journeys.py
> +            result = string1 in string2
Ah, many thanks for pointing this out! 

I've gone with a simplified approach in commits 4aaeb8fe1279c6cb1573fd46a3e75f1d4df08fe4 and 4c9b62b028d6f97c9c729a7017060ca582d76387 where `if string1 in string2 and len(string1) == len(string2)`, which I think solves the issue, as I cannot think of a time where this would not work. Can you find problems with this approach?

2022-08-17 14:15 UTC, st-alice commented on notebooks/create_and_analyse_intended_journeys.ipynb
> +    "'https://signin.account.gov.uk/contact-us')\n",
It might be worthwhile to allow the user (analyst) to choose whether they want to order by ascending or descending - as it will depend on the pages in the journey, and therefore the user's domain knowledge. For now, as the ranking method might change, I will leave it as it is; but, if we keep this original method then I will add this functionality to the function.

2022-08-17 14:15 UTC, st-alice commented on notebooks/create_and_analyse_intended_journeys.ipynb
> +    "!git clone -b all-simple-paths https://github.com/alphagov/single-data-environment-user-journeys.git -q"
Yes. Note to change `all-simple-paths` to `main` before merge

2022-08-17 14:17 UTC, st-alice commented on notebooks/create_and_analyse_intended_journeys.ipynb
> +    "]\n",
Nice - many thanks for pointing this out. As performance is not an issue I'll leave as it is but appreciate the comment for my learning (I must admit, I do not think too much about performance, as I haven't needed to yet!)

2022-08-17 14:26 UTC, st-alice commented on notebooks/create_and_analyse_intended_journeys.ipynb
> +    "# 4.1.1: Create Bokeh plot visualising the structural and functional networks\n",
Definitely - updated in commit a71f614147ecfa3194bded4cd48984f7272f9070

2022-08-17 14:52 UTC, st-alice commented
Many thanks @nacnudus for your insightful and super helpful review. I have learnt a lot as well as significantly improving the code. I believe I have responded and actioned all comments,  mainly just awaiting your advice on whether the change the ranking method to use the function `nx.shortest_simple_paths()` with weights

2022-08-22 15:05 UTC, nacnudus approved these changes
Thanks for responding in detail to all the comments.  The detail made it easy to re-review.

Approved, pending a couple of agreed changes that don't need to be reviewed again.

2022-08-24 17:03 UTC, st-alice commented
> Thanks for responding in detail to all the comments. The detail made it easy to re-review.
> 
> Approved, pending a couple of agreed changes that don't need to be reviewed again.

2022-08-24 17:04 UTC, merged